export const ADD_SCHEDULED_DAILY_MEDICATION = 'ADD_SCHEDULED_DAILY_MEDICATION';
export const REMOVE_SCHEDULED_DAILY_MEDICATION =
  'REMOVE_SCHEDULED_DAILY_MEDICATION';
export const SCHEDULED_DAILY_MEDICATIONS_REFRESH =
  'SCHEDULED_DAILY_MEDICATIONS_REFRESH';
export const SCHEDULED_DAILY_MEDICATIONS_REFRESH_DAY =
  'SCHEDULED_DAILY_MEDICATIONS_REFRESH_DAY';
