export const ADD_MEDICATION = 'ADD_MEDICATION';
export const UPDATE_MEDICATION = 'UPDATE_MEDICATION';
export const REMOVE_MEDICATION = 'REMOVE_MEDICATION';
export const CONFIRM_CONSUMPTION = 'CONFIRM_CONSUMPTION';
